language: node_js
cache: bundler
node_js:
  - 8.10.0
services:
  - postgresql
script:
  - npm run test
after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage/lcov.info
  - npm run coverage

env:
  global:
	- NODE_ENV=test