export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const GET_ALL_BUSINESSES = 'GET_ALL_BUSINESSES';
export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const ADD_BUSINESS = 'ADD_BUSINESS';
export const VIEW_BUSINESS = 'VIEW_BUSINESS';
